"""things

Revision ID: 77bcae14035e
Revises: 5b84ce769e3c
Create Date: 2022-06-28 14:26:44.256534

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77bcae14035e"
down_revision = "5b84ce769e3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thing",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("colour", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_thing_colour"), "thing", ["colour"], unique=False)
    op.create_index(op.f("ix_thing_created_at"), "thing", ["created_at"], unique=False)
    op.create_index(op.f("ix_thing_name"), "thing", ["name"], unique=False)
    op.create_index(op.f("ix_thing_user_id"), "thing", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thing_user_id"), table_name="thing")
    op.drop_index(op.f("ix_thing_name"), table_name="thing")
    op.drop_index(op.f("ix_thing_created_at"), table_name="thing")
    op.drop_index(op.f("ix_thing_colour"), table_name="thing")
    op.drop_table("thing")
    # ### end Alembic commands ###
