"""initial migration

Revision ID: aa3b9a46fc13
Revises:
Create Date: 2022-07-27 17:03:26.468404

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa3b9a46fc13"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organisation_domain"), "organisation", ["domain"], unique=True)
    op.create_table(
        "user_account",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("timezone", sa.String(), server_default="UTC", nullable=False),
        sa.Column("organisation_id", postgresql.UUID(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("login_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_account_email_address"),
        "user_account",
        ["email_address"],
        unique=True,
    )
    op.create_index(op.f("ix_user_account_name"), "user_account", ["name"], unique=False)
    op.create_index(
        op.f("ix_user_account_organisation_id"),
        "user_account",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_account_role"), "user_account", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_account_role"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_organisation_id"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_name"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_email_address"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_organisation_domain"), table_name="organisation")
    op.drop_table("organisation")
    # ### end Alembic commands ###
